services:
  postgres:
    container_name: ${NEXT_PUBLIC_APP_SLUG:-app}-postgres
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${NEXT_PUBLIC_APP_SLUG:-app}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - ./.postgres:/var/lib/postgresql/data

  redis:
    container_name: ${NEXT_PUBLIC_APP_SLUG:-app}-redis
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ./.redis:/data

  redisinsight:
    container_name: ${NEXT_PUBLIC_APP_SLUG:-app}-redisinsight
    image: redislabs/redisinsight:latest
    restart: unless-stopped
    ports:
      - '5540:5540'
    depends_on:
      - redis

volumes:
  postgres:
  redis:
