services:
  postgres:
    container_name: repo-postgres
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: repo
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - ./.postgres:/var/lib/postgresql/data

  redis:
    container_name: repo-redis
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ./.redis:/data

volumes:
  postgres:
  redis:
